apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for MongoDB and OpenSearch..."
              until nc -z mongodb 27017 && nc -z opensearch 9200; do
                sleep 5
              done
              echo "✅ Dependencies ready!"
      containers:
        - name: graylog
          image: graylog/graylog:5.2
          env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: 89a3dde751e0faf68f4916f4a724eed8
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: http://192.168.1.250:9000/
            - name: GRAYLOG_MONGODB_URI
              value: mongodb://mongodb:27017/graylog
            - name:  GRAYLOG_ELASTICSEARCH_HOSTS
              value: https://opensearch:9200
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
          ports:
            - name: http
              containerPort: 9000
            - name: gelf
              containerPort: 12201
              protocol: UDP