apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-config
  namespace: graylog
data:
  graylog.conf: |
    password_secret = 89a3dde751e0faf68f4916f4a724eed8
    root_password_sha2 = 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    http_bind_address = 0.0.0.0:9000
    http_publish_uri = http://192.168.10.250:9000/
    mongodb_uri = mongodb://mongodb:27017/graylog
    opensearch_uri = http://opensearch:9200